image: node:8.12.0

cache:
  paths:
    - node_modules/
    - .yarn

before_script:
  - apt-get update -qq && apt-get install

stages:
  - build
  - test

Build:
  stage: build
  tags:
    - gitlab-org
  before_script:
    - yarn config set cache-folder .yarn
    - yarn
  script:
    - yarn build

Test:
  stage: test
  tags:
    - gitlab-org
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install
  script:
    - yarn test

